import { Zap, Orbit, Ghost, Snowflake, Copy, Eye, Hourglass, Flame, HeartPulse, Shield } from 'lucide-react'

export const abilities = [
  { id: 0, name: 'Max Speed', category: 'Mobility', color: 'amber', icon: Zap, cooldown: 9, range: 'Self', duration: '1 second', summary: 'Gone in a flash.', description: 'Surge forward at 3.5× your normal speed for one second. Keep moving to slip past incoming attacks.', passive: 'A motion-blur trail follows your dash.' },
  { id: 1, name: 'Teleport', category: 'Mobility', color: 'violet', icon: Orbit, cooldown: 15, range: '20 meters', duration: '1 second delay', summary: 'Rewrite your position.', description: 'Aim at a location within 20 meters and teleport there after a one-second delay. A visible marker warns opponents where you will land.', passive: null },
  { id: 2, name: 'Invisibility', category: 'Stealth', color: 'slate', icon: Ghost, cooldown: 15, range: 'Self', duration: '7 seconds', summary: 'Become the unknown.', description: 'Disappear from other players for seven seconds. Attacking ends invisibility early. All-Seeing Eye can still reveal you.', passive: null },
  { id: 3, name: 'Absolute Zero', category: 'Control', color: 'ice', icon: Snowflake, cooldown: 25, range: '10 meters', duration: '3 seconds', summary: 'Leave them frozen.', description: 'Freeze opponents within 10 meters for three seconds. Frozen players cannot move, attack, or use an ability.', passive: null },
  { id: 4, name: 'Copycat', category: 'Adaptive', color: 'violet', icon: Copy, cooldown: 10, range: '20 meters', duration: 'Stored for the match', summary: 'Their power. Your rules.', description: 'Copy the nearest awakened opponent within 20 meters. Press R to cycle stored powers; Space casts the selected one. Copied powers have a 10-second penalty plus 20% extra cooldown. Press R back to Copycat to collect another.', passive: 'Active powers only. Revives and other passives cannot be copied.' },
  { id: 5, name: 'All-Seeing Eye', category: 'Perception', color: 'amber', icon: Eye, cooldown: 25, range: '20 meters', duration: '6 seconds', summary: 'Nothing stays hidden.', description: 'Reveal all opponents within 20 meters for six seconds, even through ruins and invisibility. Revealed opponents are highlighted in the arena.', passive: null },
  { id: 6, name: 'Time Stop', category: 'Control', color: 'ice', icon: Hourglass, cooldown: 25, range: '10 meters', duration: '3 seconds', summary: 'Take a moment. Literally.', description: 'Stop nearby opponents and projectiles for three seconds while you keep moving.', passive: 'Once per match, lethal damage rewinds you to your last safe position with 40 HP.' },
  { id: 7, name: 'Phoenix', category: 'Restoration', color: 'amber', icon: Flame, cooldown: 9, range: 'Self', duration: 'Instant', summary: 'The end is a beginning.', description: 'Restore 15% of your maximum health. Use between fights to stay one step ahead of elimination.', passive: 'Revive at your current position with full health, up to three times per match.' },
  { id: 8, name: 'Blessing', category: 'Restoration', color: 'ice', icon: HeartPulse, cooldown: 25, range: 'Self', duration: 'Instant', summary: 'A second wind.', description: 'Restore 50% of your maximum health instantly, up to your 100 HP maximum. Time it carefully to turn a fight around.', passive: null },
  { id: 9, name: 'Force Field', category: 'Defense', color: 'slate', icon: Shield, cooldown: 5, range: '10 meters', duration: '3 seconds', summary: 'Hold your ground.', description: 'Create a protective field that destroys incoming projectiles. You can also activate it manually with Space.', passive: 'Automatically activates below 50 HP when off cooldown.' },
] as const

export const featuredAbilities = [0, 1, 2, 3, 7]
export type Ability = (typeof abilities)[number]
export const cooldowns = abilities.map((a) => a.cooldown)
